1713435885828	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1713438671782	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1713438671783	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1713438671783	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1713438671784	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1713438671833	Sync.SyncScheduler	DEBUG	Woke from sleep.
1713438671833	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1713438671833	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1713438671834	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1713438673835	Sync.Service	DEBUG	User-Agent: LibreWolf/124.0.2 (Linux x86_64) FxSync/1.126.0.20240401114208.desktop
1713438673835	Sync.Service	INFO	Starting sync at 2024-04-18 13:11:13 in browser session enAeo8ya7DOE
1713438673835	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1713438673836	Sync.Status	INFO	Resetting Status.
1713438673836	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1713438673837	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1713438673837	FirefoxAccounts	DEBUG	getOAuthToken enter
1713438673837	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713438673837	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713438673837	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1713438673837	Sync.SyncAuthManager	INFO	Getting sync key
1713438673838	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1713438673838	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1713438673838	FirefoxAccounts	DEBUG	getOAuthToken enter
1713438673838	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713438673838	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713438673838	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1713438673838	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1713438673839	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713438673839	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1713438673839	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713438673839	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1713438673839	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1713438673839	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1713438673839	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1713438673839	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1713438673840	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/206026008/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713438673840	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1713438673840	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1713438673840	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713438673840	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1713438673841	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1713438673844	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
