1713279100079	Sync.LogManager	DEBUG	Flushing file log
1713279100081	Sync.LogManager	DEBUG	Log cleanup threshold time: 1712415100081
1713279100084	Sync.LogManager	DEBUG	Done deleting files.
1713279100577	Sync.Engine.Tabs	INFO	Can't do a quick-sync due to the service status: <Status: login: success.login, service: error.sync.failed, sync: error.login.reason.network>
1713279140118	Sync.Collection	WARN	POST request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/206026008/storage/tabs?batch=true&commit=true failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713279140119	Sync.Engine.Tabs	WARN	quicksync sync failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713279190077	Sync.Service	DEBUG	User-Agent: LibreWolf/124.0.2 (Linux x86_64) FxSync/1.126.0.20240401114208.desktop
1713279190078	Sync.Service	INFO	Starting sync at 2024-04-16 16:53:10 in browser session qwh-YZUuDn9X
1713279190078	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1713279190081	Sync.Status	INFO	Resetting Status.
1713279190081	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1713279190081	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1713279190081	FirefoxAccounts	DEBUG	getOAuthToken enter
1713279190082	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713279190082	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713279190082	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1713279230123	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713279230123	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1713279230124	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/206026008/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713279230124	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1713279230124	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1713279230124	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713279230125	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1713279230125	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 5243388 ms.
1713279230125	Sync.SyncScheduler	DEBUG	Next sync in 5243388 ms. (why=client-backoff-schedule)
1713279230127	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
